refine run dev server script !

diff --git a/scripts/run_dev_mac b/scripts/run_dev_mac
--- a/scripts/run_dev_mac
+++ b/scripts/run_dev_mac
@@ -4,17 +4,17 @@
 res=$(docker run -d --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management 2>&1)
 # shellcheck disable=SC2181
 if [ $? -eq 0 ]; then
-    echo "successfully started RabbitMQ, now running with above container hash"
+  echo "successfully started RabbitMQ, now running with above container hash"
 else
-    substring="already in use"
-    if test "${res#*$substring}" != "$res"
-    then
-        echo "RabbitMQ already started"
-    else
-        echo "$res"
-        echo "docker run failed, fix the problem and try again"
-        exit 1
-    fi
+  substring="already in use"
+  if test "${res#*$substring}" != "$res"
+  then
+    echo "RabbitMQ already started"
+  else
+    echo "$res"
+    echo "docker run failed, fix the problem and try again"
+    exit 1
+  fi
 fi
 
 # HUME
