messing around with DB backend

diff --git a/scripts/run_dev_mac b/scripts/run_dev_mac
--- a/scripts/run_dev_mac
+++ b/scripts/run_dev_mac
@@ -1,21 +1,31 @@
 #!/bin/zsh
 
-# RabbitMQ
-res=$(docker run -d --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management 2>&1)
-# shellcheck disable=SC2181
-if [ $? -eq 0 ]; then
-  echo "successfully started RabbitMQ, now running with above container hash"
-else
-  substring="already in use"
-  if test "${res#*$substring}" != "$res"
+function check_container_start() {
+  # shellcheck disable=SC2181
+  if [ $? -eq 0 ];
   then
-    echo "RabbitMQ already started"
+      echo "successfully started container, now running with above hash"
   else
-    echo "$res"
-    echo "docker run failed, fix the problem and try again"
-    exit 1
+    substring="already in use"
+    if test "${1#*$substring}" != "$1"
+    then
+        echo "already started"
+    else
+        echo "$1"
+        echo "docker run failed, fix the problem and try again"
+        exit 1
+    fi
   fi
-fi
+}
+
+# RabbitMQ & Redis
+echo "starting RabbitMQ"
+rabbitmq=$(docker run -d --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management 2>&1)
+check_container_start "$rabbitmq"
+
+echo "starting Redis"
+redis=$(docker run -d --rm --name redis -p 6379:6379 redis 2>&1)
+check_container_start "$redis"
 
 # HUME
 echo "starting HUME with UUID $HUME_UUID"
